# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='minusVotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='plusVotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='minusVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='plusVotes',
            field=models.IntegerField(default=0),
        ),
    ]
